partners:
  mary: <a href="http://www.facebook.com/marystufflebeam">Mary Stufflebeam</a>
  andre: <a href="http://acrabb.github.com">Andr&eacute; Crabb</a>
  hayg: <a href="http://www.facebook.com/hayg.astourian">Hayg Astourian</a>

permalink: pretty
